name: Build
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[release]')"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: |
          VERSION=`jq .version src/metadata.json`
          gh release create ${VERSION} -t "Version ${VERSION}" -n "Automatically built by CI based on commit ${{ github.sha }}"
          gh release upload ${VERSION} fig-gnome-integration@fig.io.zip --clobber
        env:
          GH_TOKEN: ${{ github.token }}
